[32mINFO    [0m pytest_operator.plugin:plugin.py:675 Connecting to existing model microk8s-localhost:test on unspecified cloud
[32mINFO    [0m integration.test_exporter:test_exporter.py:49 Deploying all the applications
[32mINFO    [0m juju.model:model.py:2069 Deploying ch:amd64/jammy/mysql-test-app-37
[32mINFO    [0m juju.model:model.py:2069 Deploying ch:amd64/jammy/grafana-agent-k8s-64
[32mINFO    [0m juju.model:model.py:2069 Deploying ch:amd64/jammy/mysql-k8s-138
[32mINFO    [0m juju.model:model.py:2069 Deploying local:jammy/mysql-router-k8s-0
[32mINFO    [0m integration.test_exporter:test_exporter.py:88 Waiting for mysqlrouter to be in BlockedStatus
[32mINFO    [0m integration.test_exporter:test_exporter.py:94 Relating mysql, mysqlrouter and application
[33mWARNING [0m juju.model:model.py:1558 relate is deprecated and will be removed. Use integrate instead.
[33mWARNING [0m juju.model:model.py:1558 relate is deprecated and will be removed. Use integrate instead.
[32mINFO    [0m juju.model:model.py:2759 Waiting for model:
  mysql-router-k8s/0 [executing] waiting: 
[32mINFO    [0m juju.model:model.py:2759 Waiting for model:
  mysql-router-k8s/0 [idle] waiting: 
[32mINFO    [0m juju.model:model.py:2759 Waiting for model:
  mysql-router-k8s/0 [idle] active: 
[32mINFO    [0m juju.model:model.py:2759 Waiting for model:
  mysql-k8s/0 [idle] active: Primary
  mysql-router-k8s/0 [idle] active: 
  mysql-test-app/0 [idle] active: 
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:823 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f4be4b14be0>: Failed to establish a new connection: [Errno 111] Connection refused')': /metrics
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:823 Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f4be4bdbe80>: Failed to establish a new connection: [Errno 111] Connection refused')': /metrics
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:823 Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f4be4bdb3a0>: Failed to establish a new connection: [Errno 111] Connection refused')': /metrics
[32mINFO    [0m integration.test_exporter:test_exporter.py:125 Relating mysqlrouter with grafana agent
[33mWARNING [0m juju.model:model.py:1558 relate is deprecated and will be removed. Use integrate instead.
[33mWARNING [0m juju.model:model.py:1558 relate is deprecated and will be removed. Use integrate instead.
[33mWARNING [0m juju.model:model.py:1558 relate is deprecated and will be removed. Use integrate instead.
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:823 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f4be4bc6d40>: Failed to establish a new connection: [Errno 111] Connection refused')': /metrics
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:823 Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f4be4bc7dc0>: Failed to establish a new connection: [Errno 111] Connection refused')': /metrics
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:823 Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f4be4bc6b30>: Failed to establish a new connection: [Errno 111] Connection refused')': /metrics
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:823 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f4be4731c30>: Failed to establish a new connection: [Errno 111] Connection refused')': /metrics
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:823 Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f4be4732230>: Failed to establish a new connection: [Errno 111] Connection refused')': /metrics
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:823 Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f4be47316c0>: Failed to establish a new connection: [Errno 111] Connection refused')': /metrics
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:823 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f4be47327d0>: Failed to establish a new connection: [Errno 111] Connection refused')': /metrics
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:823 Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f4be4733880>: Failed to establish a new connection: [Errno 111] Connection refused')': /metrics
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:823 Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f4be4c70a00>: Failed to establish a new connection: [Errno 111] Connection refused')': /metrics
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:823 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f4be4c71e40>: Failed to establish a new connection: [Errno 111] Connection refused')': /metrics
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:823 Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f4be4c70e50>: Failed to establish a new connection: [Errno 111] Connection refused')': /metrics
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:823 Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f4be4c71780>: Failed to establish a new connection: [Errno 111] Connection refused')': /metrics
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:823 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f4be4c72830>: Failed to establish a new connection: [Errno 111] Connection refused')': /metrics
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:823 Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f4be4c707f0>: Failed to establish a new connection: [Errno 111] Connection refused')': /metrics
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:823 Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f4be4c71a50>: Failed to establish a new connection: [Errno 111] Connection refused')': /metrics
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:823 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f4be4732b90>: Failed to establish a new connection: [Errno 111] Connection refused')': /metrics
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:823 Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f4be4c71450>: Failed to establish a new connection: [Errno 111] Connection refused')': /metrics
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:823 Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f4be4c710c0>: Failed to establish a new connection: [Errno 111] Connection refused')': /metrics
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:823 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f4be4c72530>: Failed to establish a new connection: [Errno 111] Connection refused')': /metrics
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:823 Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f4be4c730d0>: Failed to establish a new connection: [Errno 111] Connection refused')': /metrics
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:823 Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f4be4c71480>: Failed to establish a new connection: [Errno 111] Connection refused')': /metrics
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:823 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f4be4c71d20>: Failed to establish a new connection: [Errno 111] Connection refused')': /metrics
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:823 Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f4be4c73100>: Failed to establish a new connection: [Errno 111] Connection refused')': /metrics
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:823 Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f4be4c72b30>: Failed to establish a new connection: [Errno 111] Connection refused')': /metrics
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:823 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f4be4247820>: Failed to establish a new connection: [Errno 111] Connection refused')': /metrics
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:823 Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f4be4247070>: Failed to establish a new connection: [Errno 111] Connection refused')': /metrics
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:823 Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f4be4247130>: Failed to establish a new connection: [Errno 111] Connection refused')': /metrics
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:823 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f4be4733ca0>: Failed to establish a new connection: [Errno 111] Connection refused')': /metrics
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:823 Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f4be4731cc0>: Failed to establish a new connection: [Errno 111] Connection refused')': /metrics
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:823 Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f4be42443a0>: Failed to establish a new connection: [Errno 111] Connection refused')': /metrics
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:823 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f4be4c73610>: Failed to establish a new connection: [Errno 111] Connection refused')': /metrics
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:823 Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f4be4bd83a0>: Failed to establish a new connection: [Errno 111] Connection refused')': /metrics
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:823 Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f4be4bc6f50>: Failed to establish a new connection: [Errno 111] Connection refused')': /metrics
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:823 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f4be4bc7190>: Failed to establish a new connection: [Errno 111] Connection refused')': /metrics
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:823 Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f4be4bc5330>: Failed to establish a new connection: [Errno 111] Connection refused')': /metrics
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:823 Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f4be4bc53f0>: Failed to establish a new connection: [Errno 111] Connection refused')': /metrics
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:823 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f4be4bc6c80>: Failed to establish a new connection: [Errno 111] Connection refused')': /metrics
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:823 Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f4be4bc62f0>: Failed to establish a new connection: [Errno 111] Connection refused')': /metrics
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:823 Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f4be4bc5180>: Failed to establish a new connection: [Errno 111] Connection refused')': /metrics
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:823 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f4be4247c40>: Failed to establish a new connection: [Errno 111] Connection refused')': /metrics
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:823 Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f4be4bc4d60>: Failed to establish a new connection: [Errno 111] Connection refused')': /metrics
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:823 Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f4be4bc48e0>: Failed to establish a new connection: [Errno 111] Connection refused')': /metrics
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:823 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f4be472a1a0>: Failed to establish a new connection: [Errno 111] Connection refused')': /metrics
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:823 Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f4be472a380>: Failed to establish a new connection: [Errno 111] Connection refused')': /metrics
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:823 Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f4be4728580>: Failed to establish a new connection: [Errno 111] Connection refused')': /metrics
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:823 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f4be472a6e0>: Failed to establish a new connection: [Errno 111] Connection refused')': /metrics
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:823 Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f4be4728130>: Failed to establish a new connection: [Errno 111] Connection refused')': /metrics
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:823 Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f4be4729420>: Failed to establish a new connection: [Errno 111] Connection refused')': /metrics
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:823 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f4be4728280>: Failed to establish a new connection: [Errno 111] Connection refused')': /metrics
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:823 Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f4be472b220>: Failed to establish a new connection: [Errno 111] Connection refused')': /metrics
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:823 Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f4be472a5c0>: Failed to establish a new connection: [Errno 111] Connection refused')': /metrics
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:823 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f4be47298a0>: Failed to establish a new connection: [Errno 111] Connection refused')': /metrics
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:823 Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f4be4728c10>: Failed to establish a new connection: [Errno 111] Connection refused')': /metrics
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:823 Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f4be472a0e0>: Failed to establish a new connection: [Errno 111] Connection refused')': /metrics
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:823 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f4be472a8f0>: Failed to establish a new connection: [Errno 111] Connection refused')': /metrics
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:823 Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f4be4728d30>: Failed to establish a new connection: [Errno 111] Connection refused')': /metrics
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:823 Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f4be4961e40>: Failed to establish a new connection: [Errno 111] Connection refused')': /metrics