[32mINFO    [0m pytest_operator.plugin:plugin.py:675 Connecting to existing model microk8s-localhost:test on unspecified cloud
[32mINFO    [0m integration.test_exporter:test_exporter.py:55 Deploying all the applications
[32mINFO    [0m juju.model:model.py:2069 Deploying ch:amd64/jammy/mysql-test-app-37
[32mINFO    [0m juju.model:model.py:2069 Deploying ch:amd64/jammy/mysql-k8s-138
[32mINFO    [0m juju.model:model.py:2069 Deploying ch:amd64/jammy/grafana-agent-k8s-64
[32mINFO    [0m juju.model:model.py:2069 Deploying local:jammy/mysql-router-k8s-0
[32mINFO    [0m integration.test_exporter:test_exporter.py:94 Waiting for mysqlrouter to be in BlockedStatus
[32mINFO    [0m integration.test_exporter:test_exporter.py:100 Relating mysql, mysqlrouter and application
[33mWARNING [0m juju.model:model.py:1558 relate is deprecated and will be removed. Use integrate instead.
[33mWARNING [0m juju.model:model.py:1558 relate is deprecated and will be removed. Use integrate instead.
[32mINFO    [0m juju.model:model.py:2759 Waiting for model:
  mysql-router-k8s/0 [executing] maintenance: Waiting for container
[32mINFO    [0m juju.model:model.py:2759 Waiting for model:
  mysql-router-k8s/0 [idle] waiting: 
[32mINFO    [0m juju.model:model.py:2759 Waiting for model:
  mysql-router-k8s/0 [executing] waiting: 
[32mINFO    [0m juju.model:model.py:2759 Waiting for model:
  mysql-k8s/0 [idle] active: Primary
  mysql-router-k8s/0 [idle] active: 
  mysql-test-app/0 [idle] active: 
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:823 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fe2a1915c60>: Failed to establish a new connection: [Errno 111] Connection refused')': /metrics
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:823 Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fe2a1914d90>: Failed to establish a new connection: [Errno 111] Connection refused')': /metrics
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:823 Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fe2a1916a40>: Failed to establish a new connection: [Errno 111] Connection refused')': /metrics
[32mINFO    [0m integration.test_exporter:test_exporter.py:134 Relating mysqlrouter with grafana agent
[33mWARNING [0m juju.model:model.py:1558 relate is deprecated and will be removed. Use integrate instead.
[33mWARNING [0m juju.model:model.py:1558 relate is deprecated and will be removed. Use integrate instead.
[33mWARNING [0m juju.model:model.py:1558 relate is deprecated and will be removed. Use integrate instead.
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:823 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fe2a1917070>: Failed to establish a new connection: [Errno 111] Connection refused')': /metrics
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:823 Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fe2a19165f0>: Failed to establish a new connection: [Errno 111] Connection refused')': /metrics
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:823 Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fe2a1915d20>: Failed to establish a new connection: [Errno 111] Connection refused')': /metrics
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:823 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fe2a1917730>: Failed to establish a new connection: [Errno 111] Connection refused')': /metrics
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:823 Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fe2a1916f50>: Failed to establish a new connection: [Errno 111] Connection refused')': /metrics
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:823 Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fe2a1ec1c90>: Failed to establish a new connection: [Errno 111] Connection refused')': /metrics
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:823 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fe2a1ec3160>: Failed to establish a new connection: [Errno 111] Connection refused')': /metrics
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:823 Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fe2a1ec1e40>: Failed to establish a new connection: [Errno 111] Connection refused')': /metrics
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:823 Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fe2a1ec2770>: Failed to establish a new connection: [Errno 111] Connection refused')': /metrics
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:823 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fe2a1ec0430>: Failed to establish a new connection: [Errno 111] Connection refused')': /metrics
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:823 Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fe2a1ec2f20>: Failed to establish a new connection: [Errno 111] Connection refused')': /metrics
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:823 Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fe2a1bb0e50>: Failed to establish a new connection: [Errno 111] Connection refused')': /metrics
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:823 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fe2a1e5ae00>: Failed to establish a new connection: [Errno 111] Connection refused')': /metrics
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:823 Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fe2a1e593c0>: Failed to establish a new connection: [Errno 111] Connection refused')': /metrics
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:823 Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fe2a1e5ab00>: Failed to establish a new connection: [Errno 111] Connection refused')': /metrics
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:823 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fe2a1d892a0>: Failed to establish a new connection: [Errno 111] Connection refused')': /metrics
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:823 Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fe2a1d8b670>: Failed to establish a new connection: [Errno 111] Connection refused')': /metrics
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:823 Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fe2a1bb03a0>: Failed to establish a new connection: [Errno 111] Connection refused')': /metrics
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:823 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fe2a1d8a110>: Failed to establish a new connection: [Errno 111] Connection refused')': /metrics
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:823 Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fe2a1d8b6a0>: Failed to establish a new connection: [Errno 111] Connection refused')': /metrics
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:823 Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fe2a1d8b370>: Failed to establish a new connection: [Errno 111] Connection refused')': /metrics
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:823 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fe2a1d8b970>: Failed to establish a new connection: [Errno 111] Connection refused')': /metrics
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:823 Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fe2a1d8b040>: Failed to establish a new connection: [Errno 111] Connection refused')': /metrics
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:823 Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fe2a19159c0>: Failed to establish a new connection: [Errno 111] Connection refused')': /metrics
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:823 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fe2a1915300>: Failed to establish a new connection: [Errno 111] Connection refused')': /metrics
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:823 Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fe2a1914430>: Failed to establish a new connection: [Errno 111] Connection refused')': /metrics
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:823 Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fe2a19154e0>: Failed to establish a new connection: [Errno 111] Connection refused')': /metrics
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:823 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fe2a1916350>: Failed to establish a new connection: [Errno 111] Connection refused')': /metrics
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:823 Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fe2a1914af0>: Failed to establish a new connection: [Errno 111] Connection refused')': /metrics
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:823 Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fe2a1d8a620>: Failed to establish a new connection: [Errno 111] Connection refused')': /metrics
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:823 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fe2a19141f0>: Failed to establish a new connection: [Errno 111] Connection refused')': /metrics
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:823 Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fe2a19173a0>: Failed to establish a new connection: [Errno 111] Connection refused')': /metrics
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:823 Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fe2a1915f30>: Failed to establish a new connection: [Errno 111] Connection refused')': /metrics
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:823 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fe2a1d49960>: Failed to establish a new connection: [Errno 111] Connection refused')': /metrics
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:823 Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fe2a1d49840>: Failed to establish a new connection: [Errno 111] Connection refused')': /metrics
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:823 Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fe2a1b23b50>: Failed to establish a new connection: [Errno 111] Connection refused')': /metrics
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:823 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fe2a1b239d0>: Failed to establish a new connection: [Errno 111] Connection refused')': /metrics
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:823 Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fe2a1b23dc0>: Failed to establish a new connection: [Errno 111] Connection refused')': /metrics
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:823 Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fe2a1b20400>: Failed to establish a new connection: [Errno 111] Connection refused')': /metrics
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:823 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fe2a1b22a70>: Failed to establish a new connection: [Errno 111] Connection refused')': /metrics
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:823 Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fe2a1b223b0>: Failed to establish a new connection: [Errno 111] Connection refused')': /metrics
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:823 Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fe2a1914d00>: Failed to establish a new connection: [Errno 111] Connection refused')': /metrics
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:823 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fe2a19174f0>: Failed to establish a new connection: [Errno 111] Connection refused')': /metrics
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:823 Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fe2a1916ef0>: Failed to establish a new connection: [Errno 111] Connection refused')': /metrics
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:823 Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fe2a1d49390>: Failed to establish a new connection: [Errno 111] Connection refused')': /metrics
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:823 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fe2a1b23490>: Failed to establish a new connection: [Errno 111] Connection refused')': /metrics
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:823 Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fe2a1b23970>: Failed to establish a new connection: [Errno 111] Connection refused')': /metrics
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:823 Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fe2a1b20610>: Failed to establish a new connection: [Errno 111] Connection refused')': /metrics
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:823 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fe2a1b21a20>: Failed to establish a new connection: [Errno 111] Connection refused')': /metrics
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:823 Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fe2a1b21120>: Failed to establish a new connection: [Errno 111] Connection refused')': /metrics
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:823 Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fe2a1b22fe0>: Failed to establish a new connection: [Errno 111] Connection refused')': /metrics
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:823 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fe2a1b23460>: Failed to establish a new connection: [Errno 111] Connection refused')': /metrics
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:823 Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fe2a1b21db0>: Failed to establish a new connection: [Errno 111] Connection refused')': /metrics
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:823 Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fe2a1917940>: Failed to establish a new connection: [Errno 111] Connection refused')': /metrics
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:823 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fe2a1b209d0>: Failed to establish a new connection: [Errno 111] Connection refused')': /metrics
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:823 Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fe2a1b20be0>: Failed to establish a new connection: [Errno 111] Connection refused')': /metrics
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:823 Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fe2a1b22dd0>: Failed to establish a new connection: [Errno 111] Connection refused')': /metrics