[32mINFO    [0m pytest_operator.plugin:plugin.py:675 Connecting to existing model microk8s-localhost:test on unspecified cloud
[33mWARNING [0m juju.client.connection:connection.py:927 unexpected facade UserSecretsDrain received from the controller
[33mWARNING [0m juju.client.connection:connection.py:927 unexpected facade UserSecretsManager received from the controller
[32mINFO    [0m integration.test_exporter:test_exporter.py:55 Deploying all the applications
[32mINFO    [0m juju.model:model.py:2069 Deploying ch:amd64/jammy/mysql-test-app-37
[32mINFO    [0m juju.model:model.py:2069 Deploying ch:amd64/jammy/grafana-agent-k8s-68
[32mINFO    [0m juju.model:model.py:2069 Deploying ch:amd64/jammy/mysql-k8s-149
[32mINFO    [0m juju.model:model.py:2069 Deploying local:jammy/mysql-router-k8s-0
[32mINFO    [0m integration.test_exporter:test_exporter.py:94 Waiting for mysqlrouter to be in BlockedStatus
[32mINFO    [0m integration.test_exporter:test_exporter.py:100 Relating mysql, mysqlrouter and application
[33mWARNING [0m juju.model:model.py:1558 relate is deprecated and will be removed. Use integrate instead.
[33mWARNING [0m juju.model:model.py:1558 relate is deprecated and will be removed. Use integrate instead.
[32mINFO    [0m juju.model:model.py:2759 Waiting for model:
  mysql-router-k8s/0 [executing] waiting: 
[32mINFO    [0m juju.model:model.py:2759 Waiting for model:
  mysql-router-k8s/0 [idle] waiting: 
[32mINFO    [0m juju.model:model.py:2759 Waiting for model:
  mysql-router-k8s/0 [executing] active: 
[32mINFO    [0m juju.model:model.py:2759 Waiting for model:
  mysql-k8s/0 [executing] active: Primary
  mysql-router-k8s/0 [idle] active: 
  mysql-test-app/0 [idle] active: 
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:823 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f4ad733dff0>: Failed to establish a new connection: [Errno 111] Connection refused')': /metrics
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:823 Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f4ad733ce20>: Failed to establish a new connection: [Errno 111] Connection refused')': /metrics
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:823 Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f4ad733e9e0>: Failed to establish a new connection: [Errno 111] Connection refused')': /metrics
[32mINFO    [0m integration.test_exporter:test_exporter.py:134 Relating mysqlrouter with grafana agent
[33mWARNING [0m juju.model:model.py:1558 relate is deprecated and will be removed. Use integrate instead.
[33mWARNING [0m juju.model:model.py:1558 relate is deprecated and will be removed. Use integrate instead.
[33mWARNING [0m juju.model:model.py:1558 relate is deprecated and will be removed. Use integrate instead.
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:823 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f4ad733d240>: Failed to establish a new connection: [Errno 111] Connection refused')': /metrics
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:823 Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f4ad733f490>: Failed to establish a new connection: [Errno 111] Connection refused')': /metrics
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:823 Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f4ad733efe0>: Failed to establish a new connection: [Errno 111] Connection refused')': /metrics
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:823 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f4ad733cca0>: Failed to establish a new connection: [Errno 111] Connection refused')': /metrics
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:823 Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f4ad6feb9d0>: Failed to establish a new connection: [Errno 111] Connection refused')': /metrics
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:823 Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f4ad6ff4820>: Failed to establish a new connection: [Errno 111] Connection refused')': /metrics
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:823 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f4ad6ff4430>: Failed to establish a new connection: [Errno 111] Connection refused')': /metrics
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:823 Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f4ad6ff7c10>: Failed to establish a new connection: [Errno 111] Connection refused')': /metrics
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:823 Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f4ad733f520>: Failed to establish a new connection: [Errno 111] Connection refused')': /metrics
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:823 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f4ad733faf0>: Failed to establish a new connection: [Errno 111] Connection refused')': /metrics
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:823 Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f4ad733eef0>: Failed to establish a new connection: [Errno 111] Connection refused')': /metrics
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:823 Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f4ad733fe80>: Failed to establish a new connection: [Errno 111] Connection refused')': /metrics
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:823 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f4ad733ee90>: Failed to establish a new connection: [Errno 111] Connection refused')': /metrics
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:823 Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f4ad733f790>: Failed to establish a new connection: [Errno 111] Connection refused')': /metrics
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:823 Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f4ad733e140>: Failed to establish a new connection: [Errno 111] Connection refused')': /metrics
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:823 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f4ad733d150>: Failed to establish a new connection: [Errno 111] Connection refused')': /metrics
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:823 Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f4ad733c2e0>: Failed to establish a new connection: [Errno 111] Connection refused')': /metrics
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:823 Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f4ad733f160>: Failed to establish a new connection: [Errno 111] Connection refused')': /metrics
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:823 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f4ad733f5e0>: Failed to establish a new connection: [Errno 111] Connection refused')': /metrics
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:823 Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f4ad733fc10>: Failed to establish a new connection: [Errno 111] Connection refused')': /metrics
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:823 Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f4ad733c0a0>: Failed to establish a new connection: [Errno 111] Connection refused')': /metrics
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:823 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f4ad733d3f0>: Failed to establish a new connection: [Errno 111] Connection refused')': /metrics
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:823 Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f4ad733cfa0>: Failed to establish a new connection: [Errno 111] Connection refused')': /metrics
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:823 Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f4ad6ff4640>: Failed to establish a new connection: [Errno 111] Connection refused')': /metrics
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:823 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f4ad6e55120>: Failed to establish a new connection: [Errno 111] Connection refused')': /metrics
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:823 Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f4ad6e55ed0>: Failed to establish a new connection: [Errno 111] Connection refused')': /metrics
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:823 Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f4ad7300a90>: Failed to establish a new connection: [Errno 111] Connection refused')': /metrics
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:823 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f4ad70d2920>: Failed to establish a new connection: [Errno 111] Connection refused')': /metrics
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:823 Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f4ad70d2f80>: Failed to establish a new connection: [Errno 111] Connection refused')': /metrics
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:823 Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f4ad70d1b70>: Failed to establish a new connection: [Errno 111] Connection refused')': /metrics
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:823 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f4ad70d3a00>: Failed to establish a new connection: [Errno 111] Connection refused')': /metrics
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:823 Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f4ad70d0cd0>: Failed to establish a new connection: [Errno 111] Connection refused')': /metrics
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:823 Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f4ad7303e50>: Failed to establish a new connection: [Errno 111] Connection refused')': /metrics
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:823 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f4ad70d3be0>: Failed to establish a new connection: [Errno 111] Connection refused')': /metrics
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:823 Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f4ad70d3a60>: Failed to establish a new connection: [Errno 111] Connection refused')': /metrics
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:823 Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f4ad70d08e0>: Failed to establish a new connection: [Errno 111] Connection refused')': /metrics
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:823 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f4ad70d35b0>: Failed to establish a new connection: [Errno 111] Connection refused')': /metrics
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:823 Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f4ad70d1ab0>: Failed to establish a new connection: [Errno 111] Connection refused')': /metrics
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:823 Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f4ad70d0130>: Failed to establish a new connection: [Errno 111] Connection refused')': /metrics
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:823 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f4ad70d2e90>: Failed to establish a new connection: [Errno 111] Connection refused')': /metrics
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:823 Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f4ad70d2200>: Failed to establish a new connection: [Errno 111] Connection refused')': /metrics
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:823 Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f4ad70d1b40>: Failed to establish a new connection: [Errno 111] Connection refused')': /metrics
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:823 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f4ad70d1570>: Failed to establish a new connection: [Errno 111] Connection refused')': /metrics
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:823 Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f4ad73f2740>: Failed to establish a new connection: [Errno 111] Connection refused')': /metrics
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:823 Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f4ad70d15a0>: Failed to establish a new connection: [Errno 111] Connection refused')': /metrics
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:823 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f4ad733df60>: Failed to establish a new connection: [Errno 111] Connection refused')': /metrics
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:823 Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f4ad73f0a00>: Failed to establish a new connection: [Errno 111] Connection refused')': /metrics
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:823 Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f4ad73f2b90>: Failed to establish a new connection: [Errno 111] Connection refused')': /metrics
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:823 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f4ad73f12d0>: Failed to establish a new connection: [Errno 111] Connection refused')': /metrics
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:823 Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f4ad73f0430>: Failed to establish a new connection: [Errno 111] Connection refused')': /metrics
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:823 Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f4ad73f3c10>: Failed to establish a new connection: [Errno 111] Connection refused')': /metrics
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:823 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f4ad73f1690>: Failed to establish a new connection: [Errno 111] Connection refused')': /metrics
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:823 Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f4ad73f3940>: Failed to establish a new connection: [Errno 111] Connection refused')': /metrics
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:823 Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f4ad73f3d60>: Failed to establish a new connection: [Errno 111] Connection refused')': /metrics
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:823 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f4ad73f2140>: Failed to establish a new connection: [Errno 111] Connection refused')': /metrics
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:823 Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f4ad73f2a10>: Failed to establish a new connection: [Errno 111] Connection refused')': /metrics
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:823 Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f4ad70d36a0>: Failed to establish a new connection: [Errno 111] Connection refused')': /metrics