[32mINFO    [0m pytest_operator.plugin:plugin.py:790 Model status:

Model  Controller          Cloud/Region        Version  SLA          Timestamp
test   microk8s-localhost  microk8s/localhost  3.4.3    unsupported  01:36:46Z

App                       Version  Status   Scale  Charm                     Channel        Rev  Address         Exposed  Message
data-integrator                    waiting    0/1  data-integrator           latest/edge     27                  no       installing agent
mysql-k8s                          waiting    0/3  mysql-k8s                 8.0/edge       149                  no       installing agent
mysql-router-k8s                   waiting      1  mysql-router-k8s                           0                  no       installing agent
mysql-test-app            0.0.2    waiting      1  mysql-test-app            latest/edge     37  10.152.183.71   no       installing agent
self-signed-certificates           waiting    0/1  self-signed-certificates  latest/stable   72  10.152.183.121  no       installing agent

Unit                         Workload  Agent       Address      Ports  Message
data-integrator/0*           waiting   allocating                      agent initialising
mysql-k8s/0                  waiting   allocating                      installing agent
mysql-k8s/1                  waiting   allocating                      installing agent
mysql-k8s/2                  waiting   allocating                      installing agent
mysql-router-k8s/0*          error     idle                            hook failed: "certificates-relation-created"
mysql-test-app/0*            waiting   idle        10.1.181.72         
self-signed-certificates/0*  waiting   allocating  10.1.181.74         agent initialising

[32mINFO    [0m pytest_operator.plugin:plugin.py:796 Juju error logs:

unit-mysql-router-k8s-0: 01:36:46 ERROR unit.mysql-router-k8s/0.juju-log certificates:9: Uncaught exception while in charm code:
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-mysql-router-k8s-0/charm/./src/kubernetes_charm.py", line 312, in <module>
    ops.main.main(KubernetesRouterCharm)
  File "/var/lib/juju/agents/unit-mysql-router-k8s-0/charm/venv/ops/main.py", line 441, in main
    _emit_charm_event(charm, dispatcher.event_name)
  File "/var/lib/juju/agents/unit-mysql-router-k8s-0/charm/venv/ops/main.py", line 149, in _emit_charm_event
    event_to_emit.emit(*args, **kwargs)
  File "/var/lib/juju/agents/unit-mysql-router-k8s-0/charm/venv/ops/framework.py", line 344, in emit
    framework._emit(event)
  File "/var/lib/juju/agents/unit-mysql-router-k8s-0/charm/venv/ops/framework.py", line 841, in _emit
    self._reemit(event_path)
  File "/var/lib/juju/agents/unit-mysql-router-k8s-0/charm/venv/ops/framework.py", line 930, in _reemit
    custom_handler(event)
  File "/var/lib/juju/agents/unit-mysql-router-k8s-0/charm/lib/charms/tempo_k8s/v1/charm_tracing.py", line 544, in wrapped_function
    return callable(*args, **kwargs)  # type: ignore
  File "/var/lib/juju/agents/unit-mysql-router-k8s-0/charm/src/relations/tls.py", line 277, in _on_tls_relation_created
    self._relation.request_certificate_creation()
  File "/var/lib/juju/agents/unit-mysql-router-k8s-0/charm/src/relations/tls.py", line 143, in request_certificate_creation
    csr = self._generate_csr(self.key.encode("utf-8"))
  File "/var/lib/juju/agents/unit-mysql-router-k8s-0/charm/src/relations/tls.py", line 117, in _generate_csr
    return tls_certificates.generate_csr(
  File "/var/lib/juju/agents/unit-mysql-router-k8s-0/charm/lib/charms/tls_certificates_interface/v1/tls_certificates.py", line 819, in generate_csr
    _sans.extend([x509.IPAddress(IPv4Address(san)) for san in sans_ip])
  File "/var/lib/juju/agents/unit-mysql-router-k8s-0/charm/lib/charms/tls_certificates_interface/v1/tls_certificates.py", line 819, in <listcomp>
    _sans.extend([x509.IPAddress(IPv4Address(san)) for san in sans_ip])
  File "/usr/lib/python3.10/ipaddress.py", line 1305, in __init__
    self._ip = self._ip_int_from_string(addr_str)
  File "/usr/lib/python3.10/ipaddress.py", line 1192, in _ip_int_from_string
    raise AddressValueError("Expected 4 octets in %r" % ip_str)
ipaddress.AddressValueError: Expected 4 octets in 'None'

[32mINFO    [0m pytest_operator.plugin:plugin.py:862 Forgetting main...
[31m[1mERROR   [0m websockets.client:protocol.py:1015 data transfer failed
Traceback (most recent call last):
  File "/home/runner/work/mysql-router-k8s-operator/mysql-router-k8s-operator/.tox/integration/lib/python3.10/site-packages/websockets/legacy/protocol.py", line 959, in transfer_data
    message = await self.read_message()
  File "/home/runner/work/mysql-router-k8s-operator/mysql-router-k8s-operator/.tox/integration/lib/python3.10/site-packages/websockets/legacy/protocol.py", line 1029, in read_message
    frame = await self.read_data_frame(max_size=self.max_size)
  File "/home/runner/work/mysql-router-k8s-operator/mysql-router-k8s-operator/.tox/integration/lib/python3.10/site-packages/websockets/legacy/protocol.py", line 1104, in read_data_frame
    frame = await self.read_frame(max_size)
  File "/home/runner/work/mysql-router-k8s-operator/mysql-router-k8s-operator/.tox/integration/lib/python3.10/site-packages/websockets/legacy/protocol.py", line 1161, in read_frame
    frame = await Frame.read(
  File "/home/runner/work/mysql-router-k8s-operator/mysql-router-k8s-operator/.tox/integration/lib/python3.10/site-packages/websockets/legacy/framing.py", line 68, in read
    data = await reader(2)
  File "/usr/lib/python3.10/asyncio/streams.py", line 708, in readexactly
    await self._wait_for_data('readexactly')
  File "/usr/lib/python3.10/asyncio/streams.py", line 501, in _wait_for_data
    await self._waiter
  File "/usr/lib/python3.10/asyncio/selector_events.py", line 924, in write
    n = self._sock.send(data)
OSError: [Errno 9] Bad file descriptor