{"uid":"4b4757e66a1912dae1a509f688f20b0f","children":[{"name":"Test defects","children":[{"name":"urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='10.1.58.9', port=49152): Max retries exceeded with url: /metrics (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f9875197a30>: Failed to establish a new connection: [Errno 111] Connection refused'))","children":[{"name":"test_exporter_endpoint","uid":"de33b8d409833ff1","parentUid":"856b5619ca03c0d1413baba2c20f5b00","status":"broken","time":{"start":1718501790798,"stop":1718502096290,"duration":305492},"flaky":false,"newFailed":false,"newPassed":false,"newBroken":false,"retriesCount":1,"retriesStatusChange":true,"parameters":[],"tags":["asyncio","abort_on_fail","group(1)"]}],"uid":"856b5619ca03c0d1413baba2c20f5b00"}],"uid":"bdbf199525818fae7a8651db9eafe741"}],"name":"categories"}