{"uid":"4b4757e66a1912dae1a509f688f20b0f","children":[{"name":"Test defects","children":[{"name":"urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='10.1.201.76', port=49152): Max retries exceeded with url: /metrics (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f40fec63340>: Failed to establish a new connection: [Errno 111] Connection refused'))","children":[{"name":"test_exporter_endpoint","uid":"797ad6e16d96f824","parentUid":"483d0d9760430e6a4225b14d8d71f340","status":"broken","time":{"start":1713058349800,"stop":1713058500700,"duration":150900},"flaky":false,"newFailed":false,"newPassed":false,"newBroken":false,"retriesCount":0,"retriesStatusChange":false,"parameters":[],"tags":["asyncio","abort_on_fail","group(1)"]}],"uid":"483d0d9760430e6a4225b14d8d71f340"},{"name":"juju.errors.JujuUnitError: Unit in error: mysql-router-k8s/0","children":[{"name":"test_build_and_deploy","uid":"50b2f6c31c4eaa8c","parentUid":"cf468523029120b5388938b1040064a8","status":"broken","time":{"start":1713058366669,"stop":1713058401705,"duration":35036},"flaky":false,"newFailed":false,"newPassed":false,"newBroken":true,"retriesCount":0,"retriesStatusChange":false,"parameters":[],"tags":["asyncio","abort_on_fail","@pytest.mark.skipif(False, reason='Skips juju <3.1.x as we have a dependency for self-signed-certificates')","group(1)"]}],"uid":"cf468523029120b5388938b1040064a8"}],"uid":"bdbf199525818fae7a8651db9eafe741"}],"name":"categories"}