{"uid":"4b4757e66a1912dae1a509f688f20b0f","children":[{"name":"Test defects","children":[{"name":"urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='10.1.115.138', port=49152): Max retries exceeded with url: /metrics (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f0f36699e10>: Failed to establish a new connection: [Errno 111] Connection refused'))","children":[{"name":"test_exporter_endpoint","uid":"da124e4586c1ddb8","parentUid":"631d87ed1f435f6ad60c117b9de38779","status":"broken","time":{"start":1714959384449,"stop":1714959677875,"duration":293426},"flaky":false,"newFailed":false,"newPassed":false,"newBroken":false,"retriesCount":0,"retriesStatusChange":false,"parameters":[],"tags":["asyncio","abort_on_fail","group(1)"]}],"uid":"631d87ed1f435f6ad60c117b9de38779"},{"name":"juju.errors.JujuAppError: App in error: mysql-k8s","children":[{"name":"test_build_and_deploy","uid":"ef7938fb5628c198","parentUid":"58957a07ef4aa3b07a27f59de0c131af","status":"broken","time":{"start":1714959413199,"stop":1714959461651,"duration":48452},"flaky":false,"newFailed":false,"newPassed":false,"newBroken":true,"retriesCount":0,"retriesStatusChange":false,"parameters":[],"tags":["asyncio","abort_on_fail","@pytest.mark.skipif(False, reason='Skips juju <3.1.x as we have a dependency for self-signed-certificates')","group(1)"]}],"uid":"58957a07ef4aa3b07a27f59de0c131af"}],"uid":"bdbf199525818fae7a8651db9eafe741"}],"name":"categories"}